services:
  api:
    container_name: api
    build: .
    entrypoint: ./docker-entrypoint.sh
    ports:
      - 8008:8000
    env_file:
      - .env
    environment:
      - API_REDIS_HOST=cache
    depends_on:
      - db
      - cache
    volumes:
      - ./:/src

  db:
    container_name: pg_db
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    expose:
      - 5432
    env_file:
      - .env

  cache:
    container_name: redis
    image: redis:alpine
    restart: always
    env_file:
      - .env
    expose:
      - 6379
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local